package org.mystic.game.model.content.minigames.fightcave;

public enum Wave {

	WAVE_0(new int[] { NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_1(new int[] { NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_2(new int[] { NPCS_DETAILS.TZ_KEK }),

	WAVE_3(new int[] { NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_4(new int[] { NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_5(new int[] { NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_6(new int[] { NPCS_DETAILS.TOK_XIL }),

	WAVE_7(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH }),

	WAVE_8(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_9(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK }),

	WAVE_10(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_11(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_12(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_13(new int[] { NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TOK_XIL }),

	WAVE_14(new int[] { NPCS_DETAILS.YT_MEJKOT }),

	WAVE_15(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KIH }),

	WAVE_16(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_17(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK }),

	WAVE_18(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_19(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_20(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK, }),

	WAVE_21(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL }),

	WAVE_22(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH }),

	WAVE_23(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_24(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK }),

	WAVE_25(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_26(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH,
			NPCS_DETAILS.TZ_KIH }),

	WAVE_27(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_28(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TOK_XIL }),

	WAVE_29(new int[] { NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.YT_MEJKOT }),

	WAVE_30(new int[] { NPCS_DETAILS.KET_ZEK }),

	WAVE_31(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_32(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_33(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_34(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_35(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_36(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_37(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL }),

	WAVE_38(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH }),

	WAVE_39(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_40(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK }),

	WAVE_41(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_42(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH,
			NPCS_DETAILS.TZ_KIH }),

	WAVE_43(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_44(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TOK_XIL }),

	WAVE_45(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT }),

	WAVE_46(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KIH }),

	WAVE_47(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_48(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK }),

	WAVE_49(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH }),

	WAVE_50(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KIH,
			NPCS_DETAILS.TZ_KIH }),

	WAVE_51(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TZ_KEK, NPCS_DETAILS.TZ_KEK }),

	WAVE_52(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL }),

	WAVE_53(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH }),

	WAVE_54(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KIH,
			NPCS_DETAILS.TZ_KIH }),

	WAVE_55(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK }),

	WAVE_56(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK,
			NPCS_DETAILS.TZ_KIH }),

	WAVE_57(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK,
			NPCS_DETAILS.TZ_KIH, NPCS_DETAILS.TZ_KIH }),

	WAVE_58(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TZ_KEK,
			NPCS_DETAILS.TZ_KEK }),

	WAVE_59(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.TOK_XIL, NPCS_DETAILS.TOK_XIL }),

	WAVE_60(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.YT_MEJKOT, NPCS_DETAILS.YT_MEJKOT }),

	WAVE_61(new int[] { NPCS_DETAILS.KET_ZEK, NPCS_DETAILS.KET_ZEK }),

	WAVE_62(new int[] { NPCS_DETAILS.TZTOK_JAD });

	public static final class NPCS_DETAILS {

		public static final short TZ_KIH = 2627;

		public static final short TZ_KEK_SPAWN = 2738;

		public static final short TZ_KEK = 2630;

		public static final short TOK_XIL = 2631;

		public static final short YT_MEJKOT = 2741;

		public static final short KET_ZEK = 2743;

		public static final short TZTOK_JAD = 2745;

	}

	private final int[] npcs;

	private Wave(int[] npcs) {
		this.npcs = npcs;
	}

	public int[] getNpcs() {
		return npcs;
	}

	public int toInteger() {
		return ordinal();
	}
}
